### ISSUE TITLE
增加API之后无法添加成功用户

### ISSUE THREAD

**Issue by imace3** [jm33-m0/gfw_scripts#4]
同题。

还是最后提示出错。

goroutine 1 [running]:
panic(0x5ffae0, 0xc4200150b0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
main.addUser(0x7ffde90de864, 0xe, 0x7ffde90de873, 0x8, 0xc420014e2a, 0x4, 0xc420014e2f, 0x8)
	/home/jm33/builds/gfw_scripts/userManager/loadUserDatabase.go:27 +0x474
main.main()
	/home/jm33/builds/gfw_scripts/userManager/loadUserDatabase.go:77 +0x6bc

[-] Something went wrong...

**Comment by jm33-m0** [comment]
前面应该有具体的报错信息，你看下是不是connection refused, 如果是的话，手动运行`ssp-server`看看是不是不能运行，以及`ss-run.sh`是不是不能运行，还有`ssp.log`的日志记录如何

**Comment by imace3** [comment]
是的，connection refused。

ss-run.sh不能运行。

没有找到ssp.log.

**Comment by jm33-m0** [comment]
你去shadowsocks-plus的tools找一下新一些的脚本试试，如果是`ssp-server`不能运行提示404的话，那估计是它下载不到主程序了

**Comment by imace3** [comment]
shadowsocks-plus的tools的脚本就是跟你这一样的。

**Comment by imace3** [comment]
是否可以把上一版的没有添加api的脚本再提供下？

**Comment by jm33-m0** [comment]
那就是`ss_add.sh`

**Comment by jm33-m0** [comment]
你得搞明白添加用户的api是怎么工作的，必须得有一个http监听，然后你的api密钥正确，才可能起作用

**Comment by jm33-m0** [comment]
@imace3 讲道理，你没有去下载新的脚本，，`ss_install.sh`在这里没有更新，你得去shadowsocks-plus找更新过的版本

**Comment by imace3** [comment]
最新的一样出问题……
ss_install.sh: line 5: syntax error near unexpected token `newline'
ss_install.sh: line 5: `<!DOCTYPE html>'

**Comment by jm33-m0** [comment]
你自己找下原因吧。。之前你说不能运行的时候根本没去检查你下载的`ssp-server`能不能用，你贴的debug信息也不完整，事实上，服务端主程序的下载链接因为作者改动repo而失效了。
看这次你贴的信息也真是累人。。敢不敢把代码用顿号括起来？然后，你是如何操作的，服务器环境是什么，具体的报错又是什么。。
再open issue的时候麻烦参考一下 StackOverflow 的提问规则

**Comment by imace3** [comment]
系统环境：16.04.1 LTS (GNU/Linux 4.4.0-31-generic x86_64)

已经是用了你最新repo上的ss_install.sh。

运行
`wget https://github.com/jm33-m0/gfw_scripts/blob/master/ssplus/ss_install.sh && bash ss_install.sh`

系统提示
`--2016-08-31 10:53:11--  https://github.com/jm33-m0/gfw_scripts/blob/master/ssplus/ss_install.sh
Resolving github.com (github.com)... 192.30.253.112
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘ss_install.sh’

ss_install.sh           [ <=>                ]  53.03K  --.-KB/s    in 0.1s    

2016-08-31 10:53:12 (368 KB/s) - ‘ss_install.sh’ saved [54303]

ss_install.sh: line 5: syntax error near unexpected token `newline'
ss_install.sh: line 5: `<!DOCTYPE html>'`

**Comment by jm33-m0** [comment]
@imace3 ........服了
你倒是看看你下载来的是个啥东西啊。。。
还有啊。。我啥时候在工具页面提过那个命令？如果我在别的什么地方写错了链接，麻烦指出来，我好去改正

**Comment by jm33-m0** [comment]
@imace3 [看下这个页面，是我维护的](https://github.com/shadowsocks-plus/shadowsocks-plus/tree/master/tools)
