### ISSUE TITLE
第一次使用的json文件

### ISSUE THREAD

**Issue by qduningning** [jm33-m0/gfw_scripts#5]
json的配置文件是什么，在哪里可以找到？3Q

**Comment by RichardDon** [comment]
试试下面的，替换成你自己的配置
```
{
"server":"a.abcd.com",
"server_port":3408,
"local_port":80,
"password":"123456",
"timeout":600,
"method":"aes-128-cfb"
}
```

**Comment by jm33-m0** [comment]
[请善用搜索功能](https://github.com/shadowsocks/shadowsocks/wiki/Configuration-via-Config-File)

**Comment by qduningning** [comment]
之前都是直接用客户端。。但貌似还是不能翻。。

**Comment by RichardDon** [comment]
重启试试

**Comment by jm33-m0** [comment]
@qduningning 如果你可以看到配置面板，确保你填写的服务器配置正确，然后等待运行状态变成`已加速`，可以重启排查问题，以及换用其他设备检测效果
