### ISSUE TITLE
极路由4`互联网`页面空白

### ISSUE THREAD

**Issue by jm33-m0** [jm33-m0/gfw_scripts#6]
- 根据两个用户的反馈，他们在极路由4使用`shadow.sh`安装Shadowsocks控制面板后`互联网`页面成为空白页
- 由于手边没有极路由4可供调试，请遇到此问题的朋友在Chrome浏览器中按下`Ctrl` + `Shift` + `I`打开console，并将所有的错误信息截图，回复本issue
- 我会尽量保证所有设备的可用性
- 请使用`/api/geewan/shadowsocks`直接调出shadowsocks配置面板

**Comment by RichardDon** [comment]
啥时候在面板上增加一个启用/停止的开关哦。。。。

**Comment by jm33-m0** [comment]
@RichardDon 这个开关之前Geewan的插件是有的，我去掉了而已，
我打算把DNS污染的问题通过这一个脚本解决干净（把所有DNS请求发往shadowsocks服务器），完了再说这个开关的事情

**Comment by RichardDon** [comment]
@jm33-m0 干得漂亮！！！真是非常的期待。

**Comment by jm33-m0** [comment]
请参考 [这个issue](https://github.com/qiwihui/hiwifi-ss/issues/7)
