### ISSUE TITLE
刚刚用极4升级了最新的固件，重新安装插件后，不能上网了。。

### ISSUE THREAD

**Issue by xutengfei** [jm33-m0/gfw_scripts#7]
碰到两个问题，今天用极4升级了最新的固件，重新安装插件后，不能上网了。
另外，博客里说“当然你也可以把DNS请求全部发到Shadowsocks服务器解析，如果你需要那样做，请联系我添加相关教程”，有这个需求，辛苦博主大大分享下了~

**Comment by jm33-m0** [comment]
- 请具体给出如何不能上网的状况，如traceroute，ping的结果，以及nc连接国内外服务器的情况，不用域名的时候又是什么情况。
- 稍后我会更新博客添加修改DNS服务器的说明，不过你需要知道，这样做的结果是你的网络基本上完全依赖shadowsocks通道，所以稳定性可能会差一些

**Comment by xutengfei** [comment]
刚恢复了下出厂设置，上网的问题好了。。
多谢博主提醒DNS的问题
