### ISSUE TITLE
这东西怎么删除？

### ISSUE THREAD

**Issue by owenyaa** [jm33-m0/gfw_scripts#9]
我安装了之后整个界面都进不去了  怎么删除？

**Comment by jm33-m0** [comment]
你可以还原出厂设置，完了之后麻烦把issue页上的相关issue看完，我早就放了解决方案在上面。

**Comment by jm33-m0** [comment]
补充一点，`这东西`**不再维护**了，主页上说的很明白

**Comment by jm33-m0** [comment]
#6

**Comment by jm33-m0** [comment]
https://github.com/qiwihui/hiwifi-ss/issues/12
